/-
# A Lower Bound for the Diameter of Cayley Graph of Sₙ

This file contains formal statements of the lemmas and theorems from:
"A Lower Bound for the Diameter of Cayley Graph of the Symmetric Group Sₙ
Generated by (12), (12...n), (1n...2)" by G.V. Antiufeev

The Cayley graph Γ of Sₙ with generators δ = (12), r = (12...n), r⁻¹ = (1n...2).
-/

import Mathlib.GroupTheory.Perm.Basic
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.Combinatorics.Quiver.Path
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Fin.Rev

open Equiv Equiv.Perm

variable (n : ℕ) [NeZero n]

/-- The transposition (12) in Sₙ -/
def delta : Perm (Fin n) := swap 0 1

/-- The cyclic permutation r = [2 3 ... n 1], i.e., the left shift (12...n) -/
def cycleR : Perm (Fin n) := Equiv.addRight 1

/-- The full reversal s = [n n-1 ... 1] -/
def reversal : Perm (Fin n) := Fin.revPerm

/-- Distance in the Cayley graph Γ of Sₙ with generators δ, r, r⁻¹.
    This is the length of the shortest word in {δ, r, r⁻¹} representing the permutation. -/
noncomputable def cayleyDist (π₁ π₂ : Perm (Fin n)) : ℕ := sorry

/-- The orbit of π under the action of ⟨r⟩ -/
def orbit (π : Perm (Fin n)) : Set (Perm (Fin n)) :=
  { π * (cycleR n)^k | k : ℤ }

/-- Distance from a permutation to an orbit -/
noncomputable def distToOrbit (π : Perm (Fin n)) (O : Set (Perm (Fin n))) : ℕ :=
  ⨅ ξ ∈ O, cayleyDist n π ξ

namespace CayleyDiameter

/-!
## Main Lemma

For permutations π and ξ where ξ is the (π₁,πⱼ)-reversal of π,
the distance formulas I-IV hold.
-/

/-- Predicate: ξ is obtained from π by reversing the first j elements.
    That is, if π = [π₁ π₂ ... πⱼ πⱼ₊₁ ... πₙ],
    then ξ = [πⱼ πⱼ₋₁ ... π₁ πⱼ₊₁ ... πₙ]. -/
def IsReversal (j : ℕ) (hj : j ≤ n) (π ξ : Perm (Fin n)) : Prop :=
  (∀ i : Fin n, (hi : i.val < j) → ξ i = π ⟨j - 1 - i.val, by omega⟩) ∧
  (∀ i : Fin n, i.val ≥ j → ξ i = π i)

/-- Formula I: dist(π, ξ·r^(⌊j/2⌋-1)) = j(j-1) - 1 -/
theorem formula_I
    (hn : n ≥ 3)
    (j : ℕ)
    (hj_lower : 2 ≤ j)
    (hj_upper : j ≤ (n + 1) / 2)
    (π ξ : Perm (Fin n))
    (h_reversal : IsReversal n j (by omega) π ξ)
    : cayleyDist n π (ξ * (cycleR n)^(j/2 - 1)) = j * (j - 1) - 1 := by
  sorry

/-- Formula II: dist(π·r^(j-2), ξ·r^(⌈j/2⌉-1)) = j(j-1) - 1 -/
theorem formula_II
    (hn : n ≥ 3)
    (j : ℕ)
    (hj_lower : 2 ≤ j)
    (hj_upper : j ≤ (n + 1) / 2)
    (π ξ : Perm (Fin n))
    (h_reversal : IsReversal n j (by omega) π ξ)
    : cayleyDist n (π * (cycleR n)^(j - 2)) (ξ * (cycleR n)^((j + 1)/2 - 1)) = j * (j - 1) - 1 := by
  sorry

/-- Formula III: dist(π·r^(⌊j/2⌋-1), ξ) = j(j-1) - 1 -/
theorem formula_III
    (hn : n ≥ 3)
    (j : ℕ)
    (hj_lower : 2 ≤ j)
    (hj_upper : j ≤ (n + 1) / 2)
    (π ξ : Perm (Fin n))
    (h_reversal : IsReversal n j (by omega) π ξ)
    : cayleyDist n (π * (cycleR n)^(j/2 - 1)) ξ = j * (j - 1) - 1 := by
  sorry

/-- Formula IV: dist(π·r^(⌈j/2⌉-1), ξ·r^(j-2)) = j(j-1) - 1 -/
theorem formula_IV
    (hn : n ≥ 3)
    (j : ℕ)
    (hj_lower : 2 ≤ j)
    (hj_upper : j ≤ (n + 1) / 2)
    (π ξ : Perm (Fin n))
    (h_reversal : IsReversal n j (by omega) π ξ)
    : cayleyDist n (π * (cycleR n)^((j + 1)/2 - 1)) (ξ * (cycleR n)^(j - 2)) = j * (j - 1) - 1 := by
  sorry

/-!
## Main Theorem 1

The distance formula for s·r^(n-i) to the identity.
-/

/-- Theorem 1: For s = [n n-1 ... 1], r = [2 3 ... n 1], and n ≥ 4,
    the distance dist(s·r^(n-i), ()) is given by:
    ⌈n/2⌉(⌈n/2⌉-1) - 1 + ⌊n/2⌋(⌊n/2⌋-1) - 1 + f(i)
    where f(i) depends on the range of i. -/
theorem theorem_distance_formula
    (hn : n ≥ 4)
    (i : ℕ)
    (hi : 1 ≤ i ∧ i ≤ n)
    : cayleyDist n (reversal n * (cycleR n)^(n - i)) 1 =
      ((n + 1) / 2) * ((n + 1) / 2 - 1) - 1 +
      (n / 2) * (n / 2 - 1) - 1 +
      if i = 1 then n / 2 + 1
      else if i ≤ n / 2 + 2 then n / 2 - i + 4
      else i - (n + 1) / 2 := by
  sorry

/-!
## Main Theorem 2

The lower bound for the diameter.
-/

/-- The diameter of the Cayley graph Γ of Sₙ with generators (12), (12...n), (1n...2) -/
noncomputable def cayleyDiameter : ℕ :=
  ⨆ (π : Perm (Fin n)), cayleyDist n π 1

/-- Theorem 2: A lower bound for the diameter of Cayley graph of Sₙ
    generated by (12), (12...n), (1n...2) is n(n-1)/2 for n ≥ 4. -/
theorem diameter_lower_bound (hn : n ≥ 4) :
    cayleyDiameter n ≥ n * (n - 1) / 2 := by
  sorry

/-- The lower bound is achieved by considering i = 2 in Theorem 1 -/
theorem diameter_lower_bound_witness (hn : n ≥ 4) :
    cayleyDist n (reversal n * (cycleR n)^(n - 2)) 1 ≥ n * (n - 1) / 2 := by
  sorry

end CayleyDiameter
