/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 56bc23bd-55d8-4a88-9bdb-3876974b433c
-/

/-
The statement that a finite integral domain is a field is already available in Mathlib as `Finite.isField_of_domain`.
For the stronger statement that any finite domain (not necessarily commutative) is a field (Wedderburn's Little Theorem), see `Finite.isDomain_to_isField`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
A finite integral domain is a field.
-/
#check Finite.isField_of_domain