/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 01b350e5-ab31-4163-ab84-f5ee441f8574
-/

/-
We define the anti-derivative of 1/(x^2-x+1) and prove that its derivative is indeed 1/(x^2-x+1).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The anti-derivative of 1/(x^2-x+1).
-/
noncomputable def antiDerivative (x : ℝ) : ℝ := 2 / Real.sqrt 3 * Real.arctan ((2 * x - 1) / Real.sqrt 3)

/-
The derivative of antiDerivative is 1/(x^2-x+1).
-/
theorem antiDerivative_valid (x : ℝ) : HasDerivAt antiDerivative (1 / (x ^ 2 - x + 1)) x := by
  unfold antiDerivative; convert HasDerivAt.const_mul _ ( HasDerivAt.arctan <| HasDerivAt.div_const ( HasDerivAt.const_mul 2 ( hasDerivAt_id x ) |> HasDerivAt.sub <| hasDerivAt_const x 1 ) _ ) using 1 ; ring_nf;
  rw [ inv_eq_iff_eq_inv ] ; norm_num ; ring